dist: trusty
sudo: required
language: cpp
compiler: clang
install:
  - sudo pip install conan
script:
  - mkdir Build && cd Build
  - conan install .. --build missing
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
